import './globals.css';

export const metadata = { title: 'saas-analytics-pro', description: 'Generated by PromptChain Web Studio' };

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return <html lang="fr"><body>{children}</body></html>;
}
